create table manifiesto (
  id_manifiesto int generated by default as identity primary key,
  flete_total int,
  anticipo int,
  neto_a_pagar int,
  total_producido int,
  saldo_a_pagar int,
  porcentaje int
);

create table usuario (
  id_user int generated by default as identity primary key,
  fk_tipodoc varchar(2),
  num_doc varchar,
  fk_perfil int,
  p_nombre varchar(20),
  s_nombre varchar(20),
  p_apellido varchar(20),
  s_apellido varchar(20),
  telefono varchar(13),
  correo varchar(300),
  contrasena varchar(50),
  contador_id int
);

create table viaje (
  id_viaje int generated by default as identity primary key,
  fk_usuario int,
  fk_manifiesto int,
  fk_cliente int,
  fk_origen int,
  fk_destino int,
  a_favor_del_carro int,
  queda_al_carro int,
  observaciones varchar(250),
  estado boolean,
  producto varchar(250),
  fecha date
);

create table gastosxviaje (
  id_gastoxviaje int generated by default as identity primary key,
  fk_viaje int,
  fk_tipogasto int,
  valor int,
  detalles varchar(250)
);

alter table viaje add foreign key (fk_usuario) references usuario (id_user);
alter table viaje add foreign key (fk_manifiesto) references manifiesto (id_manifiesto);
alter table gastosxviaje add foreign key (fk_viaje) references viaje (id_viaje);
